### ISSUE TITLE
Fix package-lock.json npm dependencies

### ISSUE THREAD

**Issue by encadyma** [IEEEBerkeley/react-ieee#60]
`npm install` complains about package-locked webpack (4.39.3), while 'react-scripts' depends on a fixed lower version (4.39.1). I haven't looked into this extensively, but some solutions could be upgrading `react-scripts` or downgrading `webpack` on `package.json` and updating `package-lock.json` to reflect this.

**Comment by mageofboy** [comment]
Thanks for creating the issue and suggesting possible solutions. I updated package.json webpack version to match what react-scripts webpack version requirement.
